// 0
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "<unknown version>"
#define GIT_HASH "0"
#define GIT_TIME ""
#define HG_REVISION_NUMBER 0
#define HG_REVISION_HASH_STRING "0"
#define HG_TIME "-300101-0000"
